(function(){
var g,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},h="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function m(){m=function(){};h.Symbol||(h.Symbol=ba)}var ca=0;function ba(a){return"jscomp_symbol_"+(a||"")+ca++}
function n(){m();var a=h.Symbol.iterator;a||(a=h.Symbol.iterator=h.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return da(this)}});n=function(){}}function da(a){var b=0;return ea(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ea(a){n();a={next:a};a[h.Symbol.iterator]=function(){return this};return a}function p(a){n();m();n();var b=a[Symbol.iterator];return b?b.call(a):da(a)}
function q(a,b){function c(){}c.prototype=b.prototype;a.qd=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d]}function r(a,b){if(b){var c=h;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
r("Array.prototype.find",function(a){return a?a:function(a,c){a:{var b=this;b instanceof String&&(b=String(b));for(var f=b.length,e=0;e<f;e++){var k=b[e];if(a.call(c,k,e,b)){a=k;break a}}a=void 0}return a}});function t(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
r("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=t(this,a,"startsWith");a+="";var f=b.length,e=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var k=0;k<e&&c<f;)if(b[c++]!=a[k++])return!1;return k>=e}});
r("Promise",function(a){function b(a){this.f=0;this.l=void 0;this.b=[];var b=this.g();try{a(b.resolve,b.reject)}catch(x){b.reject(x)}}function c(){this.b=null}function d(a){return a instanceof b?a:new b(function(b){b(a)})}if(a)return a;c.prototype.f=function(a){this.b||(this.b=[],this.i());this.b.push(a)};c.prototype.i=function(){var a=this;this.g(function(){a.o()})};var f=h.setTimeout;c.prototype.g=function(a){f(a,0)};c.prototype.o=function(){for(;this.b&&this.b.length;){var a=this.b;this.b=[];for(var b=
0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(N){this.l(N)}}}this.b=null};c.prototype.l=function(a){this.g(function(){throw a;})};b.prototype.g=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.H),reject:a(this.i)}};b.prototype.H=function(a){if(a===this)this.i(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.J(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=
!1}c?this.G(a):this.o(a)}};b.prototype.G=function(a){var b=void 0;try{b=a.then}catch(x){this.i(x);return}"function"==typeof b?this.M(b,a):this.o(a)};b.prototype.i=function(a){this.v(2,a)};b.prototype.o=function(a){this.v(1,a)};b.prototype.v=function(a,b){if(0!=this.f)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.f);this.f=a;this.l=b;this.B()};b.prototype.B=function(){if(this.b){for(var a=this.b,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.b=null}};var e=new c;b.prototype.J=
function(a){var b=this.g();a.ta(b.resolve,b.reject)};b.prototype.M=function(a,b){var c=this.g();try{a.call(b,c.resolve,c.reject)}catch(N){c.reject(N)}};b.prototype.then=function(a,c){function d(a,b){return"function"==typeof a?function(b){try{f(a(b))}catch(bb){e(bb)}}:b}var f,e,k=new b(function(a,b){f=a;e=b});this.ta(d(a,f),d(c,e));return k};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.ta=function(a,b){function c(){switch(d.f){case 1:a(d.l);break;case 2:b(d.l);break;default:throw Error("Unexpected state: "+
d.f);}}var d=this;this.b?this.b.push(function(){e.f(c)}):e.f(c)};b.resolve=d;b.reject=function(a){return new b(function(b,c){c(a)})};b.race=function(a){return new b(function(b,c){for(var f=p(a),e=f.next();!e.done;e=f.next())d(e.value).ta(b,c)})};b.all=function(a){var c=p(a),e=c.next();return e.done?d([]):new b(function(a,b){function f(b){return function(c){k[b]=c;l--;l||a(k)}}var k=[],l=0;do k.push(void 0),l++,d(e.value).ta(f(k.length-1),b),e=c.next();while(!e.done)})};return b});
r("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}});r("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var f=b.length;for(c=c||0;c<f;c++)if(b[c]==a||Object.is(b[c],a))return!0;return!1}});r("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==t(this,a,"includes").indexOf(a,c||0)}});
r("Object.assign",function(a){return a?a:function(a,c){for(var b=1;b<arguments.length;b++){var f=arguments[b];if(f)for(var e in f)Object.prototype.hasOwnProperty.call(f,e)&&(a[e]=f[e])}return a}});r("String.prototype.endsWith",function(a){return a?a:function(a,c){var b=t(this,a,"endsWith");a+="";void 0===c&&(c=b.length);c=Math.max(0,Math.min(c|0,b.length));for(var f=a.length;0<f&&0<c;)if(b[--c]!=a[--f])return!1;return 0>=f}});
function u(){this.id="";this.za={};this.type="";this.K=this.P=0;this.Kb=this.Ib="";this.Ca=this.Da=0;this.Aa=!1;this.mb=this.lb=0;this.xb=this.wb="0";this.ob=this.nb=""};function v(){u.call(this);this.$=0;this.action=this.Wb="";this.controller=null;this.rb=[];this.Sb=[];this.sa=[]}q(v,u);h.Object.defineProperties(v.prototype,{Ba:{configurable:!0,enumerable:!0,get:function(){return this.sa.find(function(a){return a.type.startsWith("promoted_video")&&"video/mp4"===a.Y})}},Ua:{configurable:!0,enumerable:!0,get:function(){return this.sa.filter(function(a){return!a.type.startsWith("promoted_video")}).filter(function(a){return"application/x-shockwave-flash"!=a.Y})}}});function w(){u.call(this);this.id="";this.za={};this.Y=this.kb=this.Oc=this.pvId=this.detail="";this.fd=this.xa=0;this.od="";this.cb=this.V=0;this.rd=!1;this.Sc=1;this.controller={};this.Ta=this.paused=!1;this.exposed=null}q(w,u);
h.Object.defineProperties(w.prototype,{x:{configurable:!0,enumerable:!0,set:function(a){this.lb=a;this.controller.O&&this.controller.O.call(this.controller)},get:function(){return this.lb}},y:{configurable:!0,enumerable:!0,set:function(a){this.mb=a;this.controller.O&&this.controller.O.call(this.controller)},get:function(){return this.mb}},width:{configurable:!0,enumerable:!0,set:function(a){this.K=a;void 0;this.controller.O&&this.controller.O.call(this.controller)},
get:function(){return this.K}},height:{configurable:!0,enumerable:!0,set:function(a){this.P=a;this.controller.O&&this.controller.O.call(this.controller)},get:function(){return this.P}},Na:{configurable:!0,enumerable:!0,set:function(a){this.kb=a;""!=a&&(this.Ta=!0)},get:function(){return this.kb}}});function y(a){this.c=a}g=y.prototype;g.load=function(){return new Promise(function(){})};g.N=function(){};g.aa=function(){return new Promise(function(){})};g.addEventListener=function(){return!1};g.pause=function(){return!1};g.resume=function(){return!1};g.show=function(){return!1};g.ga=function(){return!1};function fa(a){a.style.cursor="pointer";a.addEventListener("mouseover",function(){a.style.cursor="none";setTimeout(function(){a.style.cursor="pointer"},100)})};function ga(a,b,c,d){c=void 0===c?null:c;d=void 0===d?null:d;var f;if(a)for(a="string"===typeof a?[{src:a}]:"SCRIPT"===a.nodeName?[a]:Array.prototype.slice.call(a),b?f=ha(b):f=document.getElementsByTagName("head")[0]||document.documentElement,b=0;a[b];b++){var e=a[b];e.parentNode&&e.parentNode.removeChild(e);var e=a[b],k=document.createElement("script"),l=e.text||e.textContent||e.innerHTML||"";if(e.src)k.src=e.src;else try{k.appendChild(document.createTextNode(l))}catch(x){k.text=l}f.appendChild(k);
c&&(k.onload=c);d&&(k.onerror=d);f.removeChild(k)}}function ha(a){return"BODY"===a.tagName?a.previousElementSibling:a.parentElement?ha(a.parentElement):null};m();var ia=Symbol("AdModel");m();var ja=Symbol("AdModel");
function z(a){if(a===ja)void 0;else throw"AdModel is a singleton: Cannot construct directly. Use 'AdModel.instance'";this.version="20160920";this.ra=[];this.b={};this.Ma=!1;this.fb=null;this.P=this.K=0;this.oc="";this.qa=this.paused=!1;this.Oa=1;this.j={};this.Gb=function(){void 0};this.va={};this.ed=this.m=null;this.eb=!1;this.jb=this.pa=this.ib=this.ua=null}
function A(){z.a.ra.forEach(function(a){return a.controller.Qb.call(a.controller)})}z.prototype.fail=function(){this.qa=!0;this.Gb()};
h.Object.defineProperties(z.prototype,{da:{configurable:!0,enumerable:!0,get:function(){return this.b},set:function(a){this.b=a}},width:{configurable:!0,enumerable:!0,set:function(a){void 0;this.K=a},get:function(){return this.K}},height:{configurable:!0,enumerable:!0,set:function(a){void 0;this.P=a},get:function(){return this.P}}});
h.Object.defineProperties(z,{a:{configurable:!0,enumerable:!0,get:function(){this[ia]||(this[ia]=new z(ja));return this[ia]}}});function ka(a){this.c=a;this.A=null}q(ka,y);g=ka.prototype;g.load=function(){var a=this;return new Promise(function(b){var c=z.a.ua;a.A=document.createElement("div");a.A.id=a.c.id;a.aa.call(a);a.A.innerHTML=a.c.detail;a.A.style.visibility="hidden";c.appendChild(a.A);ga(a.A.getElementsByTagName("script"),c);b()})};
g.aa=function(){var a=this;return new Promise(function(b){a.A.style.top=a.c.y+"px";a.A.style.left=a.c.x+"px";a.A.style.width=a.c.width+"px";a.A.style.height=a.c.height+"px";a.A.style.zIndex=a.c.xa;a.A.style.position="absolute";a.c.Ta?fa(a.A):a.A.style.cursor="default";b()})};g.addEventListener=function(a,b){this.A.addEventListener(a,b)};g.pause=function(){};g.resume=function(){};g.show=function(){this.A.style.visibility="visible"};g.ga=function(){this.A.style.visibility="hidden"};g.N=function(){this.A.parentNode.removeChild(this.A)};function la(a){this.c=a;this.s=null}q(la,y);g=la.prototype;g.load=function(){var a=this;return new Promise(function(b,c){var d=z.a.ua;a.s=document.createElement("img");a.s.onload=function(){a.c.Da=parseInt(a.s.width,10);a.c.Ca=parseInt(a.s.height,10);void 0;b()};a.s.onerror=function(){c()};a.aa.call(a);a.s.src=a.c.detail;a.s.id=a.c.id;a.s.style.visibility="hidden";d.appendChild(a.s)})};
g.aa=function(){var a=this;return new Promise(function(b){a.s.style.top=a.c.y+"px";a.s.style.left=a.c.x+"px";a.s.style.width=a.c.width+"px";a.s.style.height=a.c.height+"px";a.s.style.zIndex=a.c.xa;a.s.style.position="absolute";a.c.Ta?fa(a.s):a.s.style.cursor="default";b()})};g.addEventListener=function(a,b){this.s.addEventListener(a,b)};g.pause=function(){};g.resume=function(){};g.show=function(){this.s.style.visibility="visible"};g.ga=function(){this.s.style.visibility="hidden"};g.N=function(){this.s.parentNode.removeChild(this.s)};var ma="AdLoaded AdStarted AdStopped AdLinearChange AdExpandedChange AdRemainingTimeChange AdVolumeChange AdImpression AdVideoStart AdVideoFirstQuartile AdVideoMidpoint AdVideoThirdQuartile AdVideoComplete AdClickThru AdUserAcceptInvitation AdUserMinimize AdUserClose AdPaused AdPlaying AdLog AdError AdSkipped AdSkippableStateChange AdSizeChange AdDurationChange AdInteraction".split(" ");m();var na=Symbol("PubPlayerModel");m();var oa=Symbol("PubPlayerModel");function B(a){if(a===oa)void 0;else throw"PubPlayerModel is a singleton: Cannot construct directly. Use 'PubPlayerModel.instance'";this.g=this.l=null;this.B=0;this.i={};this.P=this.K=0;this.v="";this.o=0}
h.Object.defineProperties(B.prototype,{G:{configurable:!0,enumerable:!0,get:function(){return this.i},set:function(a){this.i=a;this.l=a.slot;this.g=a.videoSlot}},f:{configurable:!0,enumerable:!0,get:function(){return this.l},set:function(a){this.l=a;this.i.slot=this.l}},b:{configurable:!0,enumerable:!0,get:function(){return this.g},set:function(a){this.g=a;this.i.videoSlot=this.g}},width:{configurable:!0,enumerable:!0,get:function(){return this.g&&this.g.width||this.K}},height:{configurable:!0,enumerable:!0,
get:function(){return this.g&&this.g.height||this.P}},H:{configurable:!0,enumerable:!0,get:function(){return this.v},set:function(a){this.v=a}},B:{configurable:!0,enumerable:!0,get:function(){return this.o},set:function(a){this.o=a||0}}});h.Object.defineProperties(B,{a:{configurable:!0,enumerable:!0,get:function(){this[na]||(this[na]=new B(oa));return this[na]}}});function pa(a){this.c=a}q(pa,y);g=pa.prototype;g.load=function(){var a=this;return new Promise(function(b,c){a.resolve=b;b=z.a.ua;var d=document.createElement("script");d.id=a.c.id;d.src=a.c.detail;try{b.id=b.id||"tm_survey_container",window.tm_survey_container=b,window.tm_pr_survey={loadScript:ga,init:function(b){b.handshake({type:"script",assetObject:d,x:a.c.x||0,y:a.c.y||0,width:a.c.width,height:a.c.height,assetFeed:a.c,statsLog:a.sc,endCall:a.la,isLastAdPart:!0})}},ga([d],b,a.Vc.bind(a),a.Uc.bind(a))}catch(f){c()}})};
g.Vc=function(){void 0;this.resolve()};g.Uc=function(){void 0;this.resolve();this.la()};g.sc=function(a,b){z.a.j.controller.Ea.call(z.a.j.controller,a,null,b);"svystart"===a&&(window.getVPAIDAd().pauseAd(),z.a.j.controller.Ea.call(z.a.j.controller,"AdInteraction",null,b))};g.la=function(){z.a.m.C.call(z.a.m,"AdStopped")};function qa(a){function b(a,b){var c=null;null!=a&&0<a.indexOf("%")&&(c=parseInt(a,10)/100*b);return c}a.width=b(a.Kb,z.a.width)||a.width;a.height=b(a.Ib,z.a.height)||a.height;if(a.Aa&&0!=a.Ca&&0!=a.Da){var c=a.Da/a.Ca;a.Aa&&(1<c?(a.height=Math.floor(a.width/c),a.height>z.a.height&&(a.height=z.a.height,a.width=Math.floor(a.height*c))):(a.width=Math.floor(a.height*c),a.width>z.a.width&&(a.width=z.a.width,a.height=Math.floor(a.width/c))))}}
function ra(a){function b(a,b,c){b="x"==b?"width":"height";var d="",e="0";a.includes(c)?(a=p(a.split(c)),d=a.next().value,e=a.next().value):a.includes("%")?e=a:d=a;"%"==e.charAt(e.length-1)&&(e=z.a[b]*parseInt(e,10)/100);b=p([d,e]);a=b.next().value;b=b.next().value;return[a,parseInt(c+(void 0===b?"0":b),10)]}function c(a,c,e,k,l,x){var d=0;if("undefined"!==typeof c)k=c;else{c=e.includes("-")?p(b(e,a,"-")):p(b(e,a,"+"));a=c.next().value;c=c.next().value;c=p([a,c]);a=c.next().value;c=c.next().value;
switch(a){case k[0]:d=0;break;case k[1]:d=(x-l)/2;break;case k[2]:d=x-l}k=d+parseInt(c,10)}return k}a.x=c("x",a.wb,a.nb,["left","center","right"],a.width,z.a.width);a.y=c("y",a.xb,a.ob,["top","center","bottom"],a.height,z.a.height)};function sa(a){var b=new w;b.id="built-inBtIcon";b.type="overlay";b.V=0;b.xa=999;b.Y="HTML5";b.za=a;b.width=z.a.width;b.height=z.a.height-8;var c=b.width,d=b.height;b.detail='<img width="'+c+'" height="'+d+'"  src="#" style="visibility:hidden"/><span id="te-clearads-js-efrontier01cont1"><script type="text/javascript" src="'+("http:"===document.location.protocol?"http:":"https:")+"//choices.truste.com/ca?pid=efrontier01&aid=efrontier01&cid=0911ef120x240&c=efrontier01cont1&w="+c+"&h="+d+'&plc=tr&js=10">\x3c/script></span>';
b.Aa=!0;a.sa.push(b)};function ta(){}function ua(){var a="";var b=Array.prototype.slice.call(document.querySelectorAll("script")).filter(function(a){return-1<a.src.indexOf("feedURL=")});b.length?1==b.length&&(a=b[0].src):a=ta.b;return a}function C(a){var b=void 0===b?ua():b;var c="";if(b.includes("?")){b=b.split("?")[1].split("&");for(var d,f=0;f<b.length;f++)if(d=b[f].split("="),d[0]==a){c=d[1];break}}return c}h.Object.defineProperties(ta,{b:{configurable:!0,enumerable:!0,get:function(){return"http://mock.url.for.unit.test/?feedURL=&tm_auction_id=tm_auction_id_123&ad_id=ad_id_123&psId=psId_123&psIdNum=12345&id=id_123"}}});function va(){}function wa(a,b){return new Promise(function(a,d){void 0;null==b?(void 0,d("null feed")):(void 0,z.a.ed=b,xa(b),ya(b),z.a.sd=b.viewabilityStandard,b.hasOwnProperty("adParts")&&b.adParts.forEach(function(a){za(a);Aa(a)}),void 0,a())})}
function za(a){a=a.assets;var b=a.find(function(a){return"survey"===a.type&&("application/javascript"===a.mimeType||"text/javascript"===a.mimeType)});if(b){for(var c=0;c<a.length;c++)"application/x-shockwave-flash"===a[c].mimeType&&a.splice(c,1);a.push({clickURL:null,description:null,encodingRate:500,mimeType:"video/mp4",trackAsAutoplay:"T",type:"promoted_video",align:null,showDuration:null,layer:"0",timer:0,parentAssetID:null,id:1234567890,height:b.height,loops:null,inplayCall:"bannerClicks",videoDuration:30,
delay:null,framework:"vpaid",timerPos:null,pvId:"SURVEY",width:b.width,preserveAspectRatio:"T",x:"center",y:"center",detail:"https://playtime.tubemogul.com/assets/blank1x1.mp4",autoPlay:null,showControls:"F",resourceType:"static"})}}
function xa(a){var b=z.a.j;b.kc=a.adClass;b.bd=a.session.host;b.sessId=a.session.sessId;b.psId=a.psId;b.Zb=a.vtrusted;var c=C("psIdNum");b.Ya=c||a.psIdNum||a.tmSiteIdNum;"undefined"!==typeof a.pixels&&(b.L=b.L.concat(a.pixels));"undefined"!==typeof a.statsPixels&&(z.a.eb=!0,b.L=b.L.concat(a.statsPixels));b.Qa=a.feedId;a.zeroTime&&(b.gd=a.zeroTime);b.paId=a.paId;b.Ub=a.statsBaseURL;b.wa=a.cpId||C("cpId");b.ka=a.plcId||C("plcId");b.Wc=a.page_url||C("page_url");b.did=a.did||C("did");b.didtype=a.didtype||
C("didtype");b.env=a.env||C("env");b.conn=a.conn||C("conn");b.moatfees=a.moatfees||C("moatfees");b.moatenabled=a.moatenabled||C("moatenabled");b.nc=a.nc||C("nc");b.bi=a.bi||C("bi");b.price=C("price");b.sb=a.expaId||C("expaId");b.Ka=a.adEngImpQP||C("adEngImpQP");b.La=a.adEngViewQP||C("adEngViewQP");b.Ja=a.adEngClickThruQP||C("adEngClickThruQP");b.tb=a.expk||C("expk");b.Rb=a.sgrpk||C("sgrpk")}function ya(a){void 0;z.a.oc=a.assetBaseURL;z.a.Ma=a.bt}
function Aa(a){var b=new v;b.type=a.type;b.action=a.action;b.Wb=a.trigger;b.$=a.sequence;a.assets.forEach(function(a){if(-1==["companion"].indexOf(a.type)){var c=new w,f=a.preserveAspectRatio,e=a.exposed;c.id=a.id;c.za=b;c.detail=a.detail;c.type=a.type;c.Aa="string"===typeof f&&"t"===f.toLowerCase()?!0:!1;c.pvId=a.pvId;c.Oc=a.inplayCall;c.Na=a.clickURL;c.Y=a.mimeType;D(a.width,c,"w");D(a.height,c,"h");D(a.x,c,"x");D(a.y,c,"y");c.xa=a.layer;c.V=Number(a.delay);c.cb=Number(a.showDuration);c.Sc=a.loops;
c.fd=a.videoDuration;"survey"===c.type&&(c.exposed="string"===typeof e&&"f"===e.toLowerCase()?"f":"t");0<c.V&&b.rb.push(c);0<c.cb&&b.Sb.push(c);b.sa.push(c)}});z.a.Ma&&new sa(b);z.a.ra.push(b)}function D(a,b,c){var d="",f;null!=a&&""!=a&&(parseFloat(a.toString())!=Number(a)||isNaN(Number(a))?d=String(a):f=parseInt(a,10));switch(c){case "w":var e={Kb:d,width:f};break;case "h":e={Ib:d,height:f};break;case "x":e={nb:d,wb:f};break;case "y":e={ob:d,xb:f}}Object.assign(b,e)};function Ba(a){return new Promise(function(b,c){var d=new XMLHttpRequest;d.open("GET",a);d.onload=function(){200==d.status?b(d.response):c(Error(d.statusText))};d.onerror=function(){c(Error("Network Error"))};d.send()})};function Ca(){this.vb=new va;var a=this;this.rc=function(){return new Promise(function(b,c){void 0;Da(a).then(function(b){return b?wa(a.vb,b):function(a){return new Promise(function(b,c){var d=Ea();void 0;Ba(d).then(function(b){return wa(a.vb,JSON.parse(b)[0])}).catch(function(){c()}).then(b)})}(a)}).then(function(){void 0}).then(b).catch(c)})}}
function Da(a){return function(){return new Promise(function(a){try{void 0;var b=z.a.da.tm_feed;b?a(b):a(!1)}catch(d){a(!1)}})}(a)}function Ea(){void 0;void 0;var a=C("feedURL");return decodeURIComponent(a)};var Fa=null;function E(){}
function Ga(a,b){b={count:b.count,burl:b.burl,rurl:b.rurl};var c;if(location.ancestorOrigins){location.ancestorOrigins.length?(b.count=1,b.burl=window.location.href,b.rurl=location.ancestorOrigins[location.ancestorOrigins.length-1]):(b.count=0,b.burl=window.location.href);var d=Object.assign({},b)}else{a||(a=window,b.burl=window.location.href,b.count=0);try{a.location&&a.location.href&&(c=a.location.href)&&(b.burl=c)}catch(e){}try{var f=a.document.referrer;b.count=0}catch(e){b.count++}f&&(b.rurl=
f);a!=top?d=Ga(a.parent,b):d=b}return d}function Ha(a){-1<a.indexOf("facebook.com/")&&(a=a.split("?")[0]+"---REDACTED_FOR_PRIVACY---");return a}
h.Object.defineProperties(E,{f:{configurable:!0,enumerable:!0,get:function(){return"Unknown"}},g:{configurable:!0,enumerable:!0,get:function(){Fa||(Fa=Ga(null,{count:0,burl:null,rurl:null}));return Fa}},rurl:{configurable:!0,enumerable:!0,get:function(){try{var a=Ha(E.g.rurl.toString())}catch(b){a=E.f}return a}},burl:{configurable:!0,enumerable:!0,get:function(){try{var a=Ha(E.g.burl.toString())}catch(b){a=E.f}return a}},i:{configurable:!0,enumerable:!0,get:function(){if(1<E.b)var a=E.f;else 1==E.b?
a=E.rurl:E.b||(a=E.burl);return a}},b:{configurable:!0,enumerable:!0,get:function(){var a=-1;try{a=parseInt(E.g.count,10)}catch(b){}return a}}});function F(){}
function G(a,b,c,d){for(var f=[],e=3;e<arguments.length;++e)f[e-3]=arguments[e];c=void 0===c?null:c;e=p(Date().split(" "));e.next();e.next();e.next();e.next();e=e.next().value;void 0;if(!(a in F.i))void 0;else if(a!==F.l&&(a===F.b&&z.a.j.Fb&&(a=F.g),e=Math.pow(10,F.i[a]),1==Math.ceil(Math.random()*e)||"invalid_pct"===b)){void 0;var k=Ia(),l=Ja(encodeURIComponent(b),k);
c&&(l+="&msg="+encodeURIComponent(c));var x=0;f.forEach(function(a){l+="&p"+(++x).toString()+"="+encodeURIComponent(a)});l+="&smpl="+e.toString();void 0;f=new Image;a==F.b&&(f.onload=function(){z.a.fail()});f.src=l}}function Ka(a){void 0;a=a.split("?")[1].split("&");var b={ver:z.a.version};a.forEach(function(a){a=a.split("=");b[a[0]]=a[1]});return b}function Ia(){var a={ver:z.a.version};Object.assign(a,Ka(Ea()),Ka(ua()));return a}
function Ja(a,b){void 0;a="https://stats-tm.everesttech.net/stats/1/"+a+"?"+("sessId="+b.tm_auction_id);a+="&paId="+b.ad_id;a+="&psId="+b.psId;a+="&feedId="+b.id;a+="&rurl="+E.rurl;a+="&burl="+E.burl;a+="&bi="+b.bi;a+="&price="+b.price;a+="&ver="+b.ver;return a+"&rt=HTML5"}
h.Object.defineProperties(F,{b:{configurable:!0,enumerable:!0,get:function(){return 0}},g:{configurable:!0,enumerable:!0,get:function(){return 1}},f:{configurable:!0,enumerable:!0,get:function(){return 2}},l:{configurable:!0,enumerable:!0,get:function(){return 3}},v:{configurable:!0,enumerable:!0,get:function(){return 0}},G:{configurable:!0,enumerable:!0,get:function(){return 4}},B:{configurable:!0,enumerable:!0,get:function(){return 4}},o:{configurable:!0,enumerable:!0,get:function(){return-1}},
i:{configurable:!0,enumerable:!0,get:function(){return[F.v,F.G,F.B,F.o]}}});m();var La=Symbol("PubPlayerControl");m();var Ma=Symbol("PubPlayerControl");function H(a){if(a===Ma)void 0;else throw"PubPlayerControl is a singleton: Cannot construct directly. Use 'PubPlayerControl.instance'";this.c=B.a}H.prototype.b=function(a){this.c.b.setAttribute("src",a);this.c.b.load()};h.Object.defineProperties(H,{a:{configurable:!0,enumerable:!0,get:function(){this[La]||(this[La]=new H(Ma));return this[La]}}});function I(a){void 0;this.c=a;this.reject=this.resolve=null}q(I,y);g=I.prototype;g.load=function(){void 0;var a=this;return new Promise(function(b,c){a.resolve=b;a.reject=c;try{H.a.b.call(H.a,a.c.detail)}catch(d){void 0,a.reject(d)}})};g.$c=function(){this.resolve()};g.N=function(){};g.aa=function(){return Promise.resolve()};g.show=function(){};g.ga=function(){};
g.ea=function(a){var b=this;B.a.f.style.width=""+z.a.width+"px";B.a.f.style.height=""+z.a.height+"px";B.a.f.addEventListener("click",function(){return Na(b,a)});fa(B.a.f)};function Na(a,b){a.F.paused?a.F.play():b({stopPropagation:function(){},currentTarget:{id:a.c.id}})}h.Object.defineProperties(I.prototype,{F:{configurable:!0,enumerable:!0,get:function(){return H.a.c.b}}});function Oa(a){this.c=a;this.c.controller=this;this.u=null}g=Oa.prototype;g.O=function(){this.u.aa()};
g.load=function(){var a=this;return new Promise(function(b,c){if(a.c.detail&&""!=a.c.detail){switch(a.c.Y.toLowerCase()){case "video/mp4":a.u=new I(a.c);break;case "image/gif":case "text/html":case "image/png":case "image/jpeg":a.u=new la(a.c);break;case "html5":a.u=new ka(a.c);break;case "text/javascript":case "application/javascript":a.u=new pa(a.c);break;default:G(F.b,"4015","Unknown Mimetype",[a.c.Y]),c()}a.u.load().then(b(a.c))}else G(F.b,"4011","Missing asset URL",[a.c.id]),c()})};g.N=function(){this.u.N()};
g.pause=function(){};g.resume=function(){};g.ea=function(a){this.u.addEventListener("click",a)};function Pa(a){void 0;this.c=a;this.u=null;this.c.controller=this;this.i=this.g=!1;this.f=this.c.za.controller;z.a.fb=this}g=Pa.prototype;
g.load=function(){void 0;var a=this;return new Promise(function(b,c){void 0;a.c.detail&&""!=a.c.detail?(void 0,a.u=new z.a.ib(a.c),void 0,a.F=a.u.F,void 0,a.mc.call(a),void 0,a.u.load().then(function(){b(a.c)}).catch(c.bind(null,"AssetControlVideo::load : AssetRenderer*:load() failed"))):(G(0,"4011","Missing asset URL",
[a.c.id]),c())})};g.N=function(){this.u.N()};g.mc=function(){for(var a in this.b)this.F.addEventListener(a,this.b[a].bind(this))};g.start=function(){void 0;this.F.play()};g.pause=function(){this.F.pause()};g.resume=function(){this.F.play()};g.uc=function(){void 0};g.Ab=function(){void 0;this.Xb.call(this)};g.Bb=function(){void 0;this.Xb.call(this)};
g.yc=function(){void 0};g.zc=function(){void 0;this.Pb.call(this)};g.ac=function(){void 0;this.u.reject("Ad video failed to load. Unsupported src attribute on video element.")};g.Bc=function(){void 0;this.g=!0;this.i&&this.Db()};g.Ac=function(){void 0};
g.Dc=function(){void 0;var a=z.a.j.m;a.C.call(a,"AdPlaying")};g.Ec=function(){void 0};g.Ic=function(){var a=z.a.j.m;a.C.call(a,"AdVolumeChange")};g.Cc=function(){var a=z.a.j.m;a.C.call(a,"AdPaused")};g.Gc=function(){void 0};g.Hc=function(){void 0};
g.Db=function(){if(this.g)if(this.F.ended)this.Pb.call(this);else{if(z.a.j.controller.Cb.call(z.a.j.controller,this.c.pvId,this.F.currentTime,this.F.duration),this.f){var a=this.f,b=this.F.currentTime;a.c.rb.forEach(Qa(b));a.c.Sb.forEach(Ra(b))}}else this.i=!0};g.Jc=function(){void 0};
g.Xb=function(){this.F.removeEventListener("canplaythrough",this.Bb);this.F.removeEventListener("canplay",this.Ab);void 0;this.u.$c.call(this.u)};g.Pb=function(){for(var a in this.b)this.F.removeEventListener(a,this.b[a]);this.l||(this.l=!0,z.a.j.controller.Cb.call(z.a.j.controller,this.c.pvId,this.F.duration,this.F.duration))};g.ea=function(a){this.u.ea(a);return Promise.resolve()};
h.Object.defineProperties(Pa.prototype,{b:{configurable:!0,enumerable:!0,get:function(){return{abort:this.uc,canplay:this.Ab,canplaythrough:this.Bb,durationchange:this.yc,ended:this.zc,error:this.ac,loadedmetadata:this.Bc,loadstart:this.Ac,pause:this.Cc,play:this.Dc,playing:this.Ec,volumechange:this.Ic,stalled:this.Gc,suspend:this.Hc,timeupdate:this.Db,waiting:this.Jc}}}});function Sa(a){void 0;this.c=a;this.c.controller=this;this.X=[]}g=Sa.prototype;
g.Rc=function(){void 0;var a=this;return new Promise(function(b){var c=[];"player"==a.c.type&&a.c.Ba&&(a.fb=new Pa(a.c.Ba),c.push(a.fb.load()));a.c.Ua.forEach(function(a){Object.keys(a.controller).length||(a.controller=new Oa(a));c.push(a.controller.load())});Promise.all(c).then(function(b){void 0;a.X=b;void 0;a.Qb.call(a)}).then(a.lc.bind(a)).then(function(){b()})})};
g.Qb=function(){this.c.Ua.forEach(function(a){qa(a);ra(a)})};function Ta(){var a=J(K.a,K.a.b).controller;a.c.Ua.forEach(function(a){a.controller.u.show()});a.c.Ba&&a.c.Ba.controller.start()}g.lc=function(){var a=this;this.X.forEach(function(b){b.Na?b.controller.ea(a.xc.bind(a)):"click"==a.c.Wb&&"next"==a.c.action&&b.controller.ea(a.wc)})};g.wc=function(){};g.xc=function(a){a.stopPropagation();this.pause();var b=a.currentTarget.id;a=this.X.find(function(a){return a.id==b});Ua(a)};g.pause=function(){this.X.forEach(function(a){a.controller.pause()})};
g.resume=function(){this.X.forEach(function(a){a.controller.resume()})};function Va(a){a.X.forEach(function(a){void 0;a.controller.N()})}function Qa(a){return function(b){b.V<a?b.controller.u.show():b.controller.u.ga()}}function Ra(a){return function(b){var c=b.cb;isNaN(b.V)||(c+=b.V);a>c&&b.controller.u.ga()}};function Wa(a,b,c){this.ver=z.a.version;this.sessId=b.sessId;this.paId=b.paId;this.psId=b.psId;this.rt="HTML5";this.burl=E.burl;this.rurl=E.rurl;this.pw=this.w=z.a.width;this.ph=this.h=z.a.height;this.bi=b.bi;this.price=b.price;this.date=Number(new Date).toString();this.auth=b.auth;this.did=b.did;this.didtype=b.didtype;this.env=b.env;this.conn=b.conn;this.moatenabled=b.moatenabled;this.moatfees=b.moatfees;this.sb=b.sb;this.wd=b.wd.toString();this.nc=b.nc;this.vinst=b.vinst?"t":"f";switch(a){case "imp":this.inc=
"prxy"==c?"none":"view";b.vinst&&(void 0,this.vver=parseInt(z.a.jb.a.vver,10),void 0);break;case "view":this.dur=Xa(b,c);this.pvId=c;this.volume=z.a.Oa;break;case "pct25":case "pct50":case "pct75":case "pct100":this.dur=Xa(b,c);this.pvId=c;this.volume=z.a.Oa;b.Zb?this.vwbl="t":b.vinst&&(this.vwbl=z.a.pa.a.yb.call(z.a.pa.a));"prxy"!=c&&(this.st=parseInt(L(b,c).Xa,10),this.end=parseInt(L(b,c).Wa,10),this.end<this.st?(this.pct=0,G(0,"invalid_pct","Negative pct",
[this.st,this.end,this.dur],!0)):this.pct=Math.floor((this.end-this.st)/this.dur));break;case "vimp":a=Ya(z.a.pa.a);for(var d in a)this[d]=a[d]}}function Xa(a,b){void 0;void 0;void 0;return Math.floor(L(a,b).duration)};function Za(a){this.pvId=a;this.Xa=this.b=this.f=-1;this.Va=[];this.Nb=[!1,!1,!1,!1,!1];this.controller={}}h.Object.defineProperties(Za.prototype,{duration:{configurable:!0,enumerable:!0,set:function(a){this.f=a},get:function(){return this.f}},Wa:{configurable:!0,enumerable:!0,set:function(a){this.b=a},get:function(){return this.b}}});function $a(a){this.b=a;this.f=[];this.l=[];this.g=((new Date).getTime()+""+Math.floor(1E7*Math.random())).substr(0,16)}
function ab(a,b,c){document.getElementById(a.g)||(ma.forEach(function(b){a.b.subscribe(a.i.bind(a,b),b,a)}),c=b.detail.replace("${TM_CAMPAIGN_ID_NUM}",c.wa).replace("${TM_PLACEMENT_ID_NUM}",c.ka).replace("${TM_AD_ID_NUM}",c.paId).replace("${TM_SERVER_SELLER_ID_NUM}",c.ka).replace("${TM_DV_CALLBACK_NAME}",cb(a)),"Javascript"==b.type?(b=document.createElement("script"),b.id=a.g,b.src=c,document.body.appendChild(b)):void 0)}
function cb(a){var b="callback_dvGetVpaidAd_"+a.g;window[b]=function(){return{subscribe:function(b,d,f){void 0;a.b.subscribe(b,d,f);a.b.unsubscribe(a.i,d);a.l.push(d)},unsubscribe:function(b,d){void 0;a.b.unsubscribe(b,d);a.b.subscribe(a.i,d,a)},getAdVolume:function(){void 0;return a.b.getAdVolume()},getPlayer:function(){void 0;
return B.a.b},getSlot:function(){void 0;return B.a.f},getPreviousEvents:function(){void 0;for(var b=[];0<a.f.length;)b.push(a.f.shift());void 0;return b}}};return b}$a.prototype.i=function(a){this.l.includes(a)||(void 0,this.f.push(a))};m();var db=Symbol("Observer");m();var eb=Symbol("Observer");function M(a){if(a===eb)void 0;else throw"Observer is a singleton: Cannot construct directly. Use 'Observer.instance'";this.f=0;this.b=null}g=M.prototype;g.hc=function(a){this.target=a;this.b=new window.IntersectionObserver(this.Xc.bind(this),{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]})};
g.start=function(){void 0;this.b.observe(this.target);void 0;void 0};g.ic=function(){this.b.unobserve(this.target)};g.Xc=function(a){var b=this;0==a.length?this.f=0:a.forEach(function(a){b.f=a.intersectionRatio})};g.tc=function(){return this.f};
h.Object.defineProperties(M,{a:{configurable:!0,enumerable:!0,get:function(){this[db]||(this[db]=new M(eb));return this[db]}}});m();var fb=Symbol("Geometry");m();var gb=Symbol("Geometry");
function O(a){var b=this;if(a===gb)void 0;else throw"Geometry is a singleton: Cannot construct directly. Use 'Geometry.instance'";this.i=B.a.f;this.o=function(){for(var a=b.b(window),d=a.R,f=window,e;f!=window.top;)f=f.parent,e=b.b(f),e.R<d&&(d=e.R,a=e);return a};this.b=function(a){var b={width:Infinity,height:Infinity,R:Infinity};!isNaN(a.document.body.clientWidth)&&0<a.document.body.clientWidth&&(b.width=a.document.body.clientWidth);!isNaN(a.document.body.clientHeight)&&
0<a.document.body.clientHeight&&(b.height=a.document.body.clientHeight);a.document.documentElement&&a.document.documentElement.clientWidth&&!isNaN(a.document.documentElement.clientWidth)&&(b.width=a.document.documentElement.clientWidth);a.document.documentElement&&a.document.documentElement.clientHeight&&!isNaN(a.document.documentElement.clientHeight)&&(b.height=a.document.documentElement.clientHeight);a.innerWidth&&!isNaN(a.innerWidth)&&(b.width=Math.min(b.width,a.innerWidth));a.innerHeight&&!isNaN(a.innerHeight)&&
(b.height=Math.min(b.height,a.innerHeight));b.R=b.height*b.width;return b};this.f=function(a,d){var c=d.parent,e={width:0,height:0,left:0,right:0,top:0,bottom:0};a&&(e=b.g(a,d),e.width=e.right-e.left,e.height=e.bottom-e.top,d!=c&&(d=b.f(d.frameElement,c),d.bottom<e.bottom&&(d.bottom<e.top&&(e.top=d.bottom),e.bottom=d.bottom),d.right<e.right&&(d.right<e.left&&(e.left=d.right),e.right=d.right),e.width=e.right-e.left,e.height=e.bottom-e.top));return e};this.g=function(a,d){var c=d.parent,e={left:0,right:0,
top:0,bottom:0};a&&(a=a.getBoundingClientRect(),d!=c?e=b.g(d.frameElement,c):e={left:a.left+e.left,right:a.right+e.left,top:a.top+e.top,bottom:a.bottom+e.top});return e}}function hb(){try{if(window.top==window)return!0;for(var a=window;a.parent!=a;){if(a.parent.document.domain!=a.document.domain)return!1;a=a.parent}return!0}catch(b){}return!1}
O.prototype.l=function(a){var b=this.o();if(Infinity==b.R)return{error:"unmeasurable"};var c=this.i.getBoundingClientRect(),c=c.width*c.height;if(b.R/c<a)a=Math.floor(100*b.R/c);else{var d=this.b(window.top);a=this.f(this.i,window);a.bottom>d.height&&(a.height-=a.bottom-d.height);0>a.top&&(a.height+=a.top);0>a.left&&(a.width+=a.left);a.right>d.width&&(a.width-=a.right-d.width);a=Math.floor(100*a.width*a.height/c)}return{clientWidth:d.width,clientHeight:d.height,Jb:a}};
h.Object.defineProperties(O,{a:{configurable:!0,enumerable:!0,get:function(){this[fb]||(this[fb]=new O(gb));return this[fb]}}});function P(){}
h.Object.defineProperties(P,{i:{configurable:!0,enumerable:!0,get:function(){return"CH"}},o:{configurable:!0,enumerable:!0,get:function(){return"FF"}},G:{configurable:!0,enumerable:!0,get:function(){return"SF"}},v:{configurable:!0,enumerable:!0,get:function(){return"IE"}},B:{configurable:!0,enumerable:!0,get:function(){return"OP"}},l:{configurable:!0,enumerable:!0,get:function(){return"ME"}},g:{configurable:!0,enumerable:!0,get:function(){return"F0"}},H:{configurable:!0,enumerable:!0,get:function(){return"FS"}},
J:{configurable:!0,enumerable:!0,get:function(){return"FX"}},f:{configurable:!0,enumerable:!0,get:function(){try{if(window.top==window)return P.g;if(window.top.document.domain==window.document.domain)return P.H}catch(a){}return P.J}},b:{configurable:!0,enumerable:!0,get:function(){a:{for(var a=[{Z:"Edge",ba:"Edge.([0-9]+)",name:"MicroSoftEdge",code:"ME"},{Z:"Chrome",ba:"Chrome.([0-9]+)",name:"chrome",code:"CH"},{Tc:navigator.vendor,Z:"Apple",ba:"(?:Version|Safari).([1-9]?\\d)[^0-9]",name:"safari",
code:"SF"},{Z:"Opera",ba:"Version.([0-9]+)",name:"opera",code:"OP"},{Z:"Firefox",ba:"Firefox.([0-9]+)",name:"firefox",code:"FF"},{Z:"MSIE|Trident.7",ba:"(?:MSIE| rv).([0-9]+)",name:"internet explorer",code:"IE"}],b=0;b<a.length;b++)if((new RegExp(a[b].Z)).test(a[b].Tc||navigator.userAgent)){var c=new RegExp(".*"+a[b].ba+".*");a={name:a[b].name,code:a[b].code};a.version=navigator.userAgent.replace(c,"$1");c=a;break a}c=void 0}c=c||{name:"Unknown",code:"??",version:0};c.jd=c.code===P.i;c.Pc=c.code===
P.G;c.ld=c.code===P.o;c.md=c.code===P.v;c.nd=c.code===P.B;c.kd=c.code===P.l;return c}},M:{configurable:!0,enumerable:!0,get:function(){[{test:"Mac",ja:"Mac"},{test:"Win",ja:"Win"},{test:"i(Phone|Pad)",ja:"iOS"},{test:"Linux arm",ja:"Android"},{test:"Linux",ja:"Linux"}].forEach(function(a){if((new RegExp(a.test)).test(navigator.platform))return a.ja});return"Other"}}});var Q=window.BEACON_SIZE?window.BEACON_SIZE:9,ib=window.BEACON_ZINDEX?window.BEACON_ZINDEX:-9999,jb=window.BEACON_OPACITY?window.BEACON_OPACITY:.1;m();var kb=Symbol("Beacons");m();var lb=Symbol("Beacons");function R(a){if(a===lb)void 0;else throw"Beacons is a singleton: Cannot construct directly. Use 'Observer.instance'";this.ec=((new Date).getTime()+""+Math.floor(1E7*Math.random())).substr(0,16)}g=R.prototype;
g.cc=function(a){var b=this;this.S=a;this.f=[];this.b=Array(14);this.gc=B.a.f;this.fc=0;this.i=1;this.v=2;this.B=3;this.l=4;this.o=5;this.oa=6;this.hb=7;this.Fa=8;this.na=9;this.J=10;this.M=11;this.G=12;this.H=13;mb(this,!0);return new Promise(function(a,d){for(var c=[],e=0;e<b.g.length;e++){var k=new nb(b.gc,e,b.ec,b.g[e],b.vc.bind(b));b.f.push(k);c.push(ob(k))}Promise.all(c).then(b.Za.bind(b)).then(b.cd.bind(b)).then(a).catch(d)})};g.cd=function(){B.a.b.addEventListener("resize",this.Za.bind(this))};
function mb(a,b){b=void 0===b?!1:b;void 0;var c=z.a.width,d=z.a.height,f=Math.sqrt(2),e=c/(1+f),k=d/(1+f),l=c/f,f=d/f;a.g=[{name:"CONTROL",left:b?c/2:-1E4,top:b?c/2:-1E4},{name:"CENTER",left:(c-Q)/2,top:(d-Q)/2},{name:"OUTER_TOP_LEFT",left:1,top:1},{name:"OUTER_TOP_RIGHT",left:c-Q-1,top:1},{name:"OUTER_BOTTOM_LEFT",left:1,top:d-Q-1},{name:"OUTER_BOTTOM_RIGHT",left:c-Q-1,top:d-Q-1},{name:"MIDDLE_TOP_LEFT",left:(c-l-Q)/2,top:(d-f-Q)/2},{name:"MIDDLE_TOP_RIGHT",
left:(c+l-Q)/2,top:(d-f-Q)/2},{name:"MIDDLE_BOTTOM_LEFT",left:(c-l-Q)/2,top:(d+f-Q)/2},{name:"MIDDLE_BOTTOM_RIGHT",left:(c+l-Q)/2,top:(d+f-Q)/2},{name:"INNER_TOP_LEFT",left:(c-e-Q)/2,top:(d-k-Q)/2},{name:"INNER_TOP_RIGHT",left:(c+e-Q)/2,top:(d-k-Q)/2},{name:"INNER_BOTTOM_LEFT",left:(c-e-Q)/2,top:(d+k-Q)/2},{name:"INNER_BOTTOM_RIGHT",left:(c+e-Q)/2,top:(d+k-Q)/2}]}g.Za=function(){mb(this);for(var a=0;a<this.g.length;a++){var b=this.f[a].I,c=this.g[a];b.style.top=c.top+"px";b.style.left=c.left+"px"}};
g.vc=function(a){switch(a.type){case "ready":this.f[a.index].resolve();this.b[a.index]=a.state;break;case "inview":this.b[a.index]=!0;break;case "outofview":this.b[a.index]=!1}};
g.bc=function(){var a=0,b=0,c=0,d=0;if(this.b[this.fc])return"unmeasurable";for(var f=this.f.length-1,e=1;e<this.b.length;e++)if(this.b[e])switch(a++,e){case this.v:case this.B:case this.l:case this.o:b++;break;case this.oa:case this.hb:case this.Fa:case this.na:c++;break;case this.J:case this.M:case this.G:case this.H:d++}if(a===f)c="viewable";else if(100==this.S)c="unviewable";else{a:{d=[[this.v,this.oa,this.J,this.i,this.H,this.na,this.o],[this.B,this.hb,this.M,this.i,this.G,this.Fa,this.l]];for(f=
0;2>f;f++)for(var e=d[f],k=b=0;k<e.length;k++)if(a=this.b[e[k]],!0===a&&!b)b++;else if(!1===a&&1==b)b++;else if(!0===a&&2==b){a=!0;break a}a=!1}c=a?"unmeasurable":!0===this.b[this.i]&&(!0===this.b[this.v]&&!0===this.b[this.B]||!0===this.b[this.v]&&!0===this.b[this.l]||!0===this.b[this.B]&&!0===this.b[this.o]||!0===this.b[this.l]&&!0===this.b[this.o])||!0===this.b[this.i]&&4==c?"viewable":"unviewable"}return c};g.dc=function(){clearInterval(this.hd);this.f.forEach(function(a){clearInterval(a.pc);a.I.parentNode.removeChild(a.I)})};
h.Object.defineProperties(R,{a:{configurable:!0,enumerable:!0,get:function(){this[kb]||(this[kb]=new R(lb));return this[kb]}}});function nb(a,b,c,d,f){this.l=a;this.index=b;this.o="frame_"+b+c;this.f="beaconProcess_"+b+c;this.i=d;this.resolve=null;this.b="number"===typeof window.mozPaintCount;this.g=f;this.I=document.createElement("iframe")}
function ob(a){var b="";void 0;b=a.b?"parent.window."+a.f+"()":"window.frameCount = 0;var render = function(timestamp){   window.frameCount++;    requestAnimationFrame(render.bind(this));};render();parent.window."+a.f+"()";a.v="<body onload='"+b+"'></body>";pb(a);return new Promise(function(b){a.resolve=b;a.l.appendChild(a.I);a.I.id=a.o;a.I.style.cssText="position:absolute;border:none;z-index:"+ib+";opacity:"+jb+";width:"+Q+"px;height:"+Q+"px;top:"+a.i.top+"px;left:"+
a.i.left+"px;";a.I.contentWindow.document.open().write(a.v);a.I.contentWindow.document.close()})}
function pb(a){try{var b=a.l.ownerDocument;var c=b.defaultView||b.parentWindow}catch(d){b=document,c=window}c[a.f]=function(){var b=a.I.contentWindow,c=a.b?0:4,e=a.b?"mozPaintCount":"frameCount",k=!1,l=!1,x=b[e];a.pc=setInterval(function(){var d=b[e];!l&&d-x>c?(l=!0,a.g({type:"inview",index:a.index},"*")):l&&d-x<=c&&(l=!1,a.g({type:"outofview",index:a.index}));x=d;d=(16+Math.round(52*Math.random())).toString(16);b.document.body.style.background=!0===l?"#"+d+"ff"+d:"#ff"+d+d;!1===k&&(a.g({type:"ready",
index:a.index,state:l}),k=!0)},200)}};m();var qb=Symbol("ViewabilityModel");m();var rb=Symbol("ViewabilityModel");function S(a){if(a===rb)void 0;else throw"ViewabilityModel is a singleton: Cannot construct directly. Use 'ViewabilityModel.instance'";this.jc=5;this.vver=1;this.S=this.gb=-1;this.b=S.b.MRC}S.prototype.g=function(){var a=T.a;void 0;switch(a.b){case U.b:R.a.Za.call(R.a)}};
S.prototype.f=function(a){this.S=this.D.ya;null!==this.D.ia&&(this.gb=Math.ceil(1E3*this.D.ia/this.D.T));return sb(this,a)};
h.Object.defineProperties(S.prototype,{D:{configurable:!0,enumerable:!0,set:function(a){a&&a in S.b&&(this.b=S.b[a])},get:function(){return this.b}},ya:{configurable:!0,enumerable:!0,get:function(){return this.D.ya}},Ha:{configurable:!0,enumerable:!0,get:function(){return this.D.Ha}},T:{configurable:!0,enumerable:!0,get:function(){return this.D.T}},Ga:{configurable:!0,enumerable:!0,get:function(){return this.D.Ga}},ia:{configurable:!0,enumerable:!0,get:function(){return this.D.ia}},ha:{configurable:!0,
enumerable:!0,get:function(){return this.D.ha}}});h.Object.defineProperties(S,{a:{configurable:!0,enumerable:!0,get:function(){this[qb]||(this[qb]=new S(rb));return this[qb]}},b:{configurable:!0,enumerable:!0,get:function(){return{GROUPM:{ya:100,Ha:!0,T:200,Ga:!1,ia:null,ha:50},MRC:{ya:50,Ha:!1,T:200,Ga:!0,ia:2,ha:null}}}},f:{configurable:!0,enumerable:!0,get:function(){return 15}},i:{configurable:!0,enumerable:!0,get:function(){return"MRC"}},g:{configurable:!0,enumerable:!0,get:function(){return"GROUPM"}}});
m();var tb=Symbol("ViewabilityControl");m();var ub=Symbol("ViewabilityControl");
function T(a){if(a===ub)void 0;else throw"ViewabilityControl is a singleton: Cannot construct directly. Use 'ViewabilityControl.instance'";this.oa=[];this.b="NONE";this.H=!1;this.o=NaN;this.na=this.G=0;this.i=this.g=this.v=!1;this.f=0;this.J="err";this.l=null;if(a=B.a.f){try{var b=a.ownerDocument;var c=a.ownerDocument.defaultView||a.ownerDocument.parentWindow}catch(d){b=document,c=window}this.M=b;this.Fa=c}this.B=this.j=null}
function sb(a,b){var c=T.a;void 0;return new Promise(function(d){c.c=a;c.j=b;c.B=b.control;vb(c).then(function(a){wb(c);c.b=a;z.a.m.vpaidObj.subscribe(c.Tb,"AdImpression",c);z.a.m.vpaidObj.subscribe(c.Vb,"AdStopped",c);d(null)}).catch(function(){c.Ra.call(c,"ifr");d("Failed to set up a viewability measurement method")})})}
function vb(a){return new Promise(function(b,c){"number"!==typeof window.mozPaintCount&&"function"===typeof window.IntersectionObserver?(M.a.hc.call(M.a,B.a.f),b(U.f)):"number"===typeof window.mozPaintCount||P.b.Pc&&"function"===typeof window.requestAnimationFrame?R.a.cc.call(R.a,a.c.S).then(function(){return b(U.b)}).catch(function(){hb()?b(U.g):c()}):hb()?b(U.g):c()})}
function xb(a){void 0;document.fullscreenElement==B.a.b&&(a.l={Lb:a.b,Mb:a.f},a.b=U.i);["webkitbeginfullscreen","webkitendfullscreen","webkitfullscreenchange","mozfullscreenchange","fullscreenchange"].forEach(function(b){B.a.b.addEventListener(b,function(){document.fullscreenElement==B.a.b?(a.l={Lb:a.b,Mb:a.f},a.b=U.i):(a.b=a.l.Lb,a.f=a.l.Mb,a.l=null)})})}g=T.prototype;
g.yb=function(){var a;if(!(a=this.M.hidden)){var b=this.Fa.getComputedStyle(B.a.f);a=b.getPropertyValue("visibility");b=b.getPropertyValue("display");a=!("hidden"!==a&&"none"!==b)}if(a||this.c.D.Ha&&0<B.a.b.volume)return"f";switch(this.b){case U.i:return this.g=!0,this.i=!1,this.f=100,"t";case U.f:return this.f=Math.round(100*M.a.tc.call(M.a)),this.g=this.f>=this.c.S,this.i=!1,this.g?"t":"f";case U.b:return a=R.a.bc.call(R.a),this.g="viewable"===a,this.i="unmeasurable"===a,this.f=0,this.g?"t":this.i?
"err":"f";case U.g:return a=O.a.l.call(O.a,this.c.S/100),this.g=a.Jb>=this.c.S,this.i="unmeasurable"===a.error,this.f=a.Jb,this.g?"t":this.i?"ifr":"f"}return"err"};
g.Fc=function(){var a=this.yb();if("t"==a){if(null!==this.c.D.ha&&!this.H){if(0<z.a.m.vpaidObj.getAdDuration()){this.H=!0;var b=z.a.m.vpaidObj.getAdDuration()}else b=S.f;this.gb=Math.ceil(10*b*this.c.D.ha/this.c.D.T)}++this.G>=this.c.gb&&(this.v||this.Ra.call(this,a))}else"f"==a?this.c.D.Ga&&(this.G=0):++this.na>this.c.jc&&(this.v||this.Ra.call(this,a))};g.Ra=function(a){this.v=!0;this.J=a;this.B.Ea.call(this.B,"vimp")};
g.Tb=function(){void 0;z.a.m.vpaidObj.unsubscribe(this.Tb,"AdImpression");this.b===U.f&&M.a.start.call(M.a);xb(this);void 0;yb(this);this.o=setInterval(this.Fc.bind(this),this.c.D.T)};g.Vb=function(){void 0;yb(this);z.a.m.vpaidObj.unsubscribe(this.Vb,"AdStopped");switch(this.b){case U.f:M.a.b&&M.a.ic.call(M.a);break;case U.b:R.a.dc.call(R.a)}};
function yb(a){isNaN(a.o)||(clearInterval(a.o),a.o=NaN)}function Ya(a){try{var b=P.b;var c=[P.M,b.code+":"+b.version,"IF:"+P.f].join(":::")}catch(d){c="error in ViewabilityEnv::getEnvStr()"}return{vnist:"t",inc:"vview",vwbl:a.J,vver:a.c.vver,vpct:a.f,venv:c,ifr:P.f!==P.g}}function wb(a){var b=a.j;b.L&&0<b.L.length&&b.L.filter(function(a){return"Viewable"==a.trigger&&0<=a.detail.indexOf("cdn.doubleverify.com")}).forEach(function(c){var d=new $a(z.a.m.vpaidObj);ab(d,c,b);a.oa.push(d)})}
h.Object.defineProperties(T,{a:{configurable:!0,enumerable:!0,get:function(){this[tb]||(this[tb]=new T(ub));return this[tb]}}});function U(){}h.Object.defineProperties(U,{f:{configurable:!0,enumerable:!0,get:function(){return"INTERSECTION_OBSERVER"}},b:{configurable:!0,enumerable:!0,get:function(){return"IFRAME_BEACONS"}},g:{configurable:!0,enumerable:!0,get:function(){return"BROWSER_GEOMETRY"}},i:{configurable:!0,enumerable:!0,get:function(){return"FULL_SCREEN_OVERRIDE"}}});function zb(a){this.c=a;this.f={imp:"AdImpression",view:"AdVideoStart",pct25:"AdVideoFirstQuartile",pct50:"AdVideoMidpoint",pct75:"AdVideoThirdQuartile",pct100:"AdVideoComplete",eng:"AdInteraction"};this.g={imp:"Impression",view:"View",vimp:"Vimp",ct:"ClickThrough",pct25:"Complete25",pct50:"Complete50",pct75:"Complete75",pct100:"Completion",svyimp:"SurveyImpression",svystart:"SurveyStart",svycomp:"SurveyComplete"};this.b=["imp","pct25","pct50","pct75","pct100"]}
function Ua(a){var b=z.a.j.controller;a=a.Na;b.c.qb||(b.c.qb=!0,z.a.eb||(a=b.pb("ct")+"&redir="+encodeURIComponent(a)),b.ab("ct"),b.c.m.C&&b.c.m.ad.call(b.c.m,a,b.c.paId));b.c.$b(a)}g=zb.prototype;g.Cb=function(a,b,c){if(0<c&&!z.a.qa){var d=L(this.c,a);null==d&&("prxy"==a&&(this.b.shift(),this.b.unshift("view")),d=new Za(a),d.duration=c,d.Va[Math.floor(c)]=!1,this.c.ca.push(d));d.Wa=b;d.Va[Math.floor(b)]=!0;d=Ab(this,a,c);Bb(this,a,d,b);this.c.Ob=Math.floor(c-b);this.c.Yb=c}};
function Ab(a,b,c){a=L(a.c,b).Va.filter(function(a){return a}).length;return Math.min(a/c,1)}function Bb(a,b,c,d){c=Math.floor(c/.25);L(a.c,b).Nb[c]||(a.Ea(a.b[c],b).catch(function(){void 0}),L(a.c,b).Xa=d,L(a.c,b).Nb[c]=!0)}
g.Ea=function(a,b,c){b=void 0===b?null:b;var d=this;return new Promise(function(f){void 0;if(!d.c.U.hasOwnProperty(a)||0<d.c.U[a]--){"view"==a&&1==d.c.U.imp&&(void 0,G(F.f,"ViewB4Imp",["imp"+String(d.c.U.imp),"view"+String(d.c.U.view)]));var e=[];z.a.eb||e.push(d.Qc.call(d,a,b,c));e.push(d.ab.call(d,a,c));"imp"==a&&"prxy"!=b&&e.push(d.ab("view"));Promise.all(e).then(function(){void 0;d.f[a]&&(void 0,d.c.m.C.call(d.c.m,d.f[a]));f()}).catch(f)}else-5<d.c.U[a]&&(G(F.g,"DupePixel",[a+"-overBy"+String(d.c.U[a])]),f())})};g.Qc=function(a,b,c){var d=this;return new Promise(function(f){var e=d.pb.call(d,a,b,c);"imp"==a&&(d.c.Fb=!0);void 0;d.$a.call(d,e).then(function(){void 0}).then(f).catch(f)})};
g.pb=function(a,b,c){c=void 0===c?null:c;var d=this.c.protocol+this.c.Ub+"/"+a+"?";b=new Wa(a,this.c,void 0===b?null:b);var f="",e="",k;for(k in b)if("number"===typeof b[k]||b[k])e+=f+k+"="+encodeURIComponent(b[k]),f="&";d+=e;void 0;return d=Cb(this,d,a,c)};
function Cb(a,b,c,d){var f="";"imp"===c&&""!==a.c.Ka?f=a.c.Ka:"ct"===c&&""!==a.c.Ja?f=a.c.Ja:"view"===c&&""!==a.c.La&&(f=a.c.La);var e="";"view"!==c&&"imp"!==c||""===a.c.Sa||(e="&ias_vid_mon="+a.c.Sa);b=b+f+e;if(d){var f="";for(l in d)if("number"===typeof d[l]||d[l])f+="&"+l+"="+encodeURIComponent(d[l]);b+=f}d="";switch(c.toLowerCase()){case "impression":d+="&vver="+encodeURIComponent(S.a.vver.toString())+"&vw="+document.body.clientWidth+"&vh"+document.body.clientHeight;break;case "vimp":c=Ya(T.a);
for(var k in c)d+="&"+k+"="+c[k];break;case "complete25":case "complete50":case "complete75":case "completion":if(a.c.ca[0]){k=a.c.ca[0];c=parseInt(k.Xa,10);var l=parseInt(k.Wa,10);d+="&st="+c.toString()+"&end="+l.toString();d=l<c?d+"&pct=0":d+("&pct="+Math.floor((l-c)/k.duration).toString())}case "view":d+="&volume="+z.a.Oa,a.c.ca[0]&&(d+="&dur="+Math.floor(a.c.ca[0].duration))}d+="&ver="+z.a.version+"&burl="+encodeURIComponent(E.burl)+"&rurl="+encodeURIComponent(E.rurl)+"&pw="+B.a.width+"&ph="+
B.a.height+"&wd="+a.c.wd.toString();b+=d;k="";a=a.c;a.tb&&(k+="&expk="+a.tb);a.Rb&&(k+="&sgrpk="+a.Rb);return b+=k}
g.ab=function(a,b){var c=this;return new Promise(function(d){var f=[],e=c.g[a],k=c.c.L.filter(function(a){return a.trigger.toLowerCase()==e.toLowerCase()}),l=k.filter(function(a){return"flash"==a.type.toLowerCase()||"image"==a.type.toLowerCase()}),x=k.filter(function(a){return"javascript"==a.type.toLowerCase()}),N=k.filter(function(a){return"html"==a.type.toLowerCase()}),k=k.filter(function(a){return"stats"==a.type.toLowerCase()});l.forEach(function(a){return f.push(c.$a.call(c,a.detail))});x.forEach(function(a){return f.push(c.Zc.call(c,
a.detail))});N.forEach(function(a){return f.push(c.Yc.call(c,a.detail))});k.forEach(function(d){c.$a.call(c,Cb(c,d.detail,a,b))});Promise.all(f).then(function(){void 0}).then(d).catch(d)})};g.$a=function(a){return new Promise(function(b){var c=new Image;c.onload=b;c.onerror=b;try{void 0,c.src=a}catch(d){b()}})};
g.Zc=function(a){return new Promise(function(b){var c=document.createElement("script");c.type="text/javascript";c.onload=b;c.onerror=b;try{c.src=a,document.getElementsByTagName("head")[0].appendChild(c)}catch(d){b()}})};g.Yc=function(a){return new Promise(function(b){var c=document.createElement("div");c.style.visibility="hidden";document.body.appendChild(c);try{c.innerHTML=a,b()}catch(d){b()}})};function Db(){this.protocol="https://";this.Sa=this.Ja=this.La=this.Ka=this.price=this.bi=this.Ya=this.psId=this.sessId=this.bd=this.kc="";this.L=[];this.gd=new Date;this.ka=this.wa=this.paId=this.Qa="";this.Zb=this.vinst=!1;this.wd=E.b;this.Ub="stats-tm.everesttech.net/stats/1";this.control=this.controller=new zb(this);this.ca=[];this.m={};this.f=this.b=-2;this.qb=this.Fb=!1;this.moatfees=this.moatenabled=this.nc=this.conn=this.env=this.didtype=this.did=null;var a={};this.U=(a.imp=1,a.view=1,a.vimp=
2,a.pct25=1,a.pct50=1,a.pct75=1,a.pct100=1,a.ct=99,a.eng=99,a);this.$b=function(){}}function L(a,b){return a.ca.filter(function(a){return a.pvId==b})[0]}h.Object.defineProperties(Db.prototype,{Ob:{configurable:!0,enumerable:!0,set:function(a){a!=this.b&&(this.b=a,this.m.C("AdRemainingTimeChange"))},get:function(){return this.b}},Yb:{configurable:!0,enumerable:!0,set:function(a){a!=this.f&&(this.f=a,this.m.C("AdDurationChange"))},get:function(){return this.f}}});m();var Eb=Symbol("AdControlVpaidHouse");m();var Fb=Symbol("AdControlVpaidHouse");function K(a){if(a===Fb)void 0;else throw"AdControlVpaidHouse is a singleton: Cannot construct directly. Use 'AdControlVpaidHouse.instance'";this.c=z.a;this.b=-1;this.f=null}
K.prototype.g=function(){this.c.m.vpaidObj.subscribe(this.la,"AdVideoComplete",this);z.a.j.vinst=!0;this.b=-1;void 0;this.b=Gb(this);return Hb(this,J(this,this.b))};function J(a,b){var c;a.c.ra.forEach(function(a){a.$==b&&(c=a)});return c}
function Gb(a){var b=Number.MAX_VALUE,c=a.b;a.c.ra.forEach(function(a){void 0;a.$>c&&a.$<b&&(b=a.$)});void 0;void 0;return b}
function Hb(a,b){return new Promise(function(c,d){a.c.qa?(void 0,d()):(void 0,a.f=b,b.controller=new Sa(b),b.controller.Rc.call(b.controller).then(c).catch(function(b){void 0;a.f=null}))})}K.prototype.la=function(){void 0;this.f&&(Va(this.f.controller),this.c.m.C.call(this.c.m,"AdStopped"))};
h.Object.defineProperties(K,{a:{configurable:!0,enumerable:!0,get:function(){this[Eb]||(this[Eb]=new K(Fb));return this[Eb]}}});function V(a){this.Eb=new __IASVANS;this.Pa={ad_duration:void 0,volume:void 0};this.Kc={pubId:z.a.j.Ya,campId:z.a.j.wa,advId:void 0,bidurl:z.a.j.Wc,chanId:z.a.j.Qa,partner:V.b,placementId:z.a.j.ka,anId:a.Lc,uId:z.a.j.sessId,adsafe_par:""}}h.Object.defineProperties(V,{b:{configurable:!0,enumerable:!0,get:function(){return"7203"}}});function W(a,b){this.f="https://ud.tubemogul.com/js/lib/3rdparty/Ias_3.2.1.js";this.W=null;this.b=a;this.da=z.a.da;this.Lc="t"===b?V.b:b;this.load()}W.prototype.load=function(){var a=document.createElement("script");a.src=this.f;a.type="text/javascript";a.onload=this.i.bind(this);a.onerror=this.g.bind(this);document.getElementsByTagName("head")[0].appendChild(a)};
W.prototype.i=function(){try{z.a.W=new V(this);var a=B.a.b;this.W=z.a.W;try{var b=a&&"VIDEO"===a.nodeName?a:B.a.f;this.W.Eb.initCM(this.W.Kc,b);Ib(this)}catch(c){void 0}this.b(null)}catch(c){void 0,this.b(null)}};W.prototype.g=function(a){void 0;this.b(null)};
function Ib(a){"AdLoaded AdStarted AdVideoStart AdImpression AdStopped AdLinearChange AdExpandedChange AdRemainingTimeChange AdVolumeChange AdVideoFirstQuartile AdVideoMidpoint AdVideoThirdQuartile AdVideoComplete AdClickThru AdUserAcceptInvitation AdSkippableStateChange AdUserMinimize AdDurationChange AdUserClose AdPaused AdPlaying AdSizeChange AdSkipped AdError".split(" ").forEach(function(b){return z.a.j.m.vpaidObj.subscribe(Jb(a,b).bind(a),b)})}
function Jb(a,b){var c=a.W;return function(){c.Pa.volume=B.a.b.volume;c.Pa.ad_duration=z.a.j.Yb;c.Eb.sendEvent(b,c.Pa)}};function X(a,b){this.b=a;this.l=b;this.i={level1:z.a.j.wa,level2:z.a.j.ka,level3:z.a.j.Qa,level4:z.a.j.paId,slicer1:z.a.j.Ya,slicer2:null,viewmode:"normal",zMoatSID:z.a.j.sessId};this.load()}X.prototype.load=function(){var a=document.createElement("script");a.src=X.b;a.type="application/javascript";a.onload=this.g.bind(this);a.onerror=this.f.bind(this);document.getElementsByTagName("head")[0].appendChild(a)};
X.prototype.g=function(){try{initMoatTracking(this.l,B.a.f,this.i,"tubemoguljsvideo627208760992")}catch(a){void 0}this.b(null)};X.prototype.f=function(a){void 0;this.b(null)};h.Object.defineProperties(X,{b:{configurable:!0,enumerable:!0,get:function(){return"https://ud.tubemogul.com/js/lib/3rdparty/Moat_2.0.js"}}});function Kb(){this.b={};z.a.va&&z.a.va.fbd&&(this.b=Object.assign({},z.a.va.fbd));this.f=E.i}function Lb(a){return a.startsWith("http")?"function"===typeof window.URL?(new URL(a)).hostname:(a=a.match(/:\/\/([^\/$:]+\.[^\/$:]+)/))?a[1]:"NO-TOP-LEVEL-DOMAIN-IN-URL":a.split(/[\/:]/)[0]}
function Mb(a,b,c){return new Promise(function(d,f){var e=Ja("reject",Ia()),e=e+("&code="+c),e=e+("&p1="+a),e=e+("&p2="+b),e=e+"&msg=Rejected%20Ad&ssb=true"+("&wd="+E.b),k=new Image;k.onload=d;try{k.src=e}catch(l){f()}})}function Nb(a,b,c){return new Promise(function(d,f){a=a.split("${du}").join(encodeURIComponent(b)).split("${pd}").join(c);var e=new Image;e.onload=d;try{e.src=a}catch(k){f()}})};function Y(){z.a.m=this;this.bb=function(){};this.b=new Promise(function(a){return function(b,c){a.bb=function(a,f){f=void 0===f?null:f;void 0;a?b():c(f)}}}(this));this.Hb="";this.ma=[];this.vpaidObj=null}Y.prototype.ad=function(a,b){void 0;var c=this.ma.filter(function(a){return"AdClickThru"==a.Ia})[0];c&&(c.hasOwnProperty("listenerScope")?c.fa.call(c.listenerScope,a,b,!1):c.fa(a,b,!1))};
Y.prototype.C=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];var f=0,e=!1;this.ma.forEach(function(b){b.Ia==a&&("AdRemainingTimeChange"==b.Ia||void 0,e=b.hasOwnProperty("listenerScope")?b.fa.apply(b.listenerScope,c):b.fa.apply(null,c));e&&f++});return 0<f};h.Object.defineProperties(Y,{b:{configurable:!0,enumerable:!0,get:function(){return"2.0"}}});void 0;void 0;
function Ob(){G(F.f,"AdStarted...","");z.a.j=new Db;z.a.j.$b=window.open.bind(window);z.a.Gb=this.zb.bind(this);z.a.ib=I;if("undefined"==typeof Promise||"undefined"==typeof Promise.all)G(F.b,"2001","Promises not supported");else{var a=z.a,b=C("cd"),c=null;b&&(c=JSON.parse(decodeURIComponent(b)));a.va=c;this.b=new Kb;this.m=new Y;Pb.call(this.m);this.ub=new Ca;z.a.jb=S;z.a.pa=T}}g=Ob.prototype;
g.zb=function(){void 0;-1<K.a.b&&J(K.a,K.a.b)&&J(K.a,K.a.b).controller.pause();this.m.C.call(this.m,"AdError");this.m.C.call(this.m,"AdStopped")};g.qc=function(){z.a.j.m=this.m};g.Nc=function(){var a=C("moatenabled").toLowerCase();return new Promise(function(b){var c=window.getVPAIDAd;"t"===a&&"function"===typeof c?new X(b,c()):b(null)})};
g.dd=function(){var a=this;return new Promise(function(b,c){var d=a.b,f="";if(d.b&&"T"==d.b.ssb){var e=d.f;var k=d.b;e&&e!=E.f?(e=Lb(e),k=Lb(k.pd),k=e===k?"":e.endsWith("."+k)||k.endsWith("."+e)?"":"DM"):k="DI";k&&(f=k)}!z.a.qa&&0<f.length&&(k=[],k.push(Nb(d.b.aburl,d.f,d.b.pd)),k.push(Mb(d.f,d.b.pd,f)),Promise.all(k).then(z.a.fail.bind(z.a,"Rejected")));f.length?c("SSB Rejected."):b()})};
g.Mc=function(){var a=C("iasMon").toLowerCase();return new Promise(function(b){a&&"f"!==a?(z.a.j.Sa="t"===a?"tm":"account",new W(b,a)):b(null)})};
function Pb(){var a=this;this.vpaidObj={getAdLinear:function(){void 0;return!0},getAdVolume:function(){void 0;return B.a.b.volume},setAdVolume:function(b){void 0;B.a.b.volume=b;a.C("AdVolumeChange")},getAdWidth:function(){void 0;return z.a.width},getAdHeight:function(){void 0;return z.a.height},setAdWidth:function(a){void 0;z.a.width=a;A()},setAdHeight:function(a){void 0;z.a.height=a;A()},getAdExpanded:function(a){void 0;return!1},getAdSkippableState:function(){void 0;return!1},getAdRemainingTime:function(){return z.a.j.Ob},getAdDuration:function(){return Math.floor(B.a.b.duration)},getAdCompanions:function(){void 0;return""},getAdIcons:function(){return z.a.Ma},
handshakeVersion:function(a){return this.Hb=parseInt(a,10)>=parseInt(Y.b,10)?Y.b:a},initAd:function(b,c,d,f,e,k){e=void 0===e?null:e;k=void 0===k?null:k;void 0;z.a.width=b;z.a.height=c;A();B.a.H=d;B.a.B=f||0;void 0;if(e&&null!=e.AdParameters)try{z.a.da=JSON.parse(e.AdParameters),void 0,void 0}catch(l){void 0}k?(B.a.G=k,z.a.ua=k.slot,a.bb(!0)):(void 0,G(F.b,"1009","Player data missing","environmentVars"),a.bb(!1,""))},startAd:function(){void 0;a.C("AdStarted");a.C("AdImpression");a.C("AdVideoStart");Ta()},stopAd:function(){void 0;K.a.la()},pauseAd:function(){z.a.paused=!0;J(K.a,K.a.b).controller.pause()},resumeAd:function(){z.a.paused=!1;J(K.a,K.a.b).controller.resume()},
expandAd:function(){void 0},collapseAd:function(){},skipAd:function(){},resizeAd:function(b,c){void 0;z.a.width=b;z.a.height=c;A();S.a.g.call(S.a);a.C("AdSizeChange")},subscribe:function(b,c,d){d=void 0===d?null:d;void 0;b={Ia:c,fa:b};"undefined"!=typeof d&&(b.listenerScope=d);a.ma.push(b)},unsubscribe:function(b,c){a.ma=a.ma.filter(function(a){return!(a.Ia==c&&a.fa==b)})}}}
var Z=new Ob;
(function(){void 0;var a=Z.m.vpaidObj;window.getVPAIDAd=function(){void 0;return a};return Z.m.b})().then(Z.dd.bind(Z)).then(Z.ub.rc.bind(Z.ub)).then(Z.qc.bind(Z)).then(Z.Nc.bind(Z)).then(Z.Mc.bind(Z)).then(K.a.g.bind(K.a)).then(S.a.f.bind(S.a,z.a.j)).then(Z.m.C.bind(Z.m,"AdLoaded")).catch(function(a){void 0;void 0;Z.zb()});
}).call(this)

//# sourceMappingURL=vpaid.js.map
