/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(b){if(b.__qc)return b.__qc;var D="a ce cm dst enc fpa fpan je ns ogl rf tzo sr".split(" "),m=b.document,A=b.navigator,G="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),J=!1,Q=!1,K=0,H=[],g=[],E=[],p=[],f={},u=0,x=[],h=null,k={},e={},r=null,v,$=[].slice,ka,aa,R,q,B,ba,S,la,ma,na,L,ca,T,U,oa,pa,M,qa,ra,sa,ta,n,ua,F,va,V,wa,xa,da,ya,za,ea,C,Aa,N,Ba,
W,Ca,Da,X,Ea,fa,ga,Fa,ha,I,Y,O,P,ia,ja,Z,w=function(a){try{return{init:U,hash:T,push:oa,rules:Ca,hasRules:X,defaults:Fa,__qc:function(){return!0}}[a].apply(null,$.call(arguments,1))}catch(c){return!1}};w.evts=0;w.v=2;w.SD=G;w.qpixelsent=[];W=function(a){var c=a?a.length||0:0,d;for(d=0;d<c;d++)if(!a[d])return!1;return!0};ga=function(a){(a=a||b._qacct)&&(ea(p,a)||p.push(a))};ea=function(a,c){var d=a.length,b;for(b=0;b<d;b++)if(a[b]===c)return!0;return!1};N=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};
Ba=function(a){var c,d;c=N(a);if("array"===c)return a.slice(0);if("object"===c){c={};for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c}return"string"===c?""+a:a};oa=function(a,c){n(a,c)};X=function(a){return ea(E,a)};Fa=function(a,c){var d;a&&((d=k[a])&&(c=P(c,d)),c.qacct&&delete c.qacct,k[a]=c)};ha=function(a){var c,d;if(q(a))for(c in a)if("string"==typeof a[c]){c=a.event||"load";d=a.media||"webpage";"rule"!==c&&"load"!==c||"webpage"!==d&&"ad"!==d?n(a):(d=a.qacct||b._qacct,a.qacct=d,c=(c=e[d])?
P(c,a):a,e[d]=c);ga(a.qacct);break}else"object"==typeof a[c]&&null!=a[c]&&ha(a[c])};P=function(a,c){var d={};d.qacct=a.qacct||c.qacct;d.event="load"===a.event||"load"===c.event?"load":a.event&&c.event?a.event||c.event:null;d.media=null;d.media="webpage"===a.media||"webpage"===c.media?"webpage":"ad"===a.media||"ad"===c.media?"ad":a.media||c.media;da(d,a,c);da(d,c,a);d.event||delete d.event;d.media||delete d.media;return d};da=function(a,c,d){var b,s,h,e,k,f;for(b in c)c.hasOwnProperty(b)&&!a.hasOwnProperty(b)&&
(s=c[b],h=d[b],e="",k=!!s&&"string"==typeof s,f=!!h&&"string"==typeof h,k&&(e=s),k&&f&&(e+=","),f&&(e+=h),a[b]=e)};I=function(){var a=[],c,d;if(!(0<u)){Aa();for(c in e)e.hasOwnProperty(c)&&e[c]&&(d=e[c],a.push(d),delete e[c]);1==a.length&&n(a[0]);1<a.length&&n(a)}};Y=function(){var a=[],c,d,b;b=p.slice(0);for(c=0;c<b.length;c++)d=b[c],X(d)||a.push(d);if(0===a.length)I();else for(c=0;c<a.length;c++)d=a[c],E.push(d),ya(d)};za=function(){for(var a;x[0]&&("loaded"==x[0].readyState||"complete"==x[0].readyState);)a=
x.shift(),a.onreadystatechange=null,h.parentNode.insertBefore(a,h),O()};ya=function(a){var c,d;c=("https:"===m.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+a+".js";h=h||m.scripts[0];u++;d=m.createElement("script");"async"in d?(d.src=c,d.async=!1,d.onload=function(){f[a]=0;O()},d.onerror=function(){f[a]=1;O()},h.parentNode.insertBefore(d,h)):d.readyState?(f[a]=2,x.push(d),d.onreadystatechange=za,d.src=c):(f[a]=4,O())};O=function(){u-=0<u?1:0;I()};Ca=function(){var a=!0,c,d,
b;if(arguments.length){b=function(c){a?ha(c):n(c,!0)};for(c=0;c<arguments.length;c++)d=$.call(arguments[c],0),d.splice(1,0,b),Da.apply(null,d);a=!1;J&&I()}};Da=function(a,c){var d=[],b=[],e=c||n,h,k,r,y,t;if((h=$.call(arguments,2))&&h.length){k=h[0]||W;r=h[1];y=h[2];h=y.length;for(t=0;t<h;t++)d.push(!1),b.push(null);d={p:a,f:d,r:k,c:y,a:r,v:b};X(a)||E.push(a);g.push(d);Ea(d,e)}else E.push(a),f[a]=6};Ea=function(a,c){var d=a?a.c?a.c.length:0:0,b;for(b=0;b<d;b++)(function(d){var b,h;try{b=a.c[d][0],
h=a.c[d].slice(1),h.splice(0,0,function(b){a.f[d]=!0;a.v[d]=b;fa(a,c)}),b.apply(null,h)}catch(e){a.f[d]=!0,a.v[d]=!1,fa(a,c)}})(b)};fa=function(a,c){var d=a.a,b=a.v,h=a.r||W,e,k,f,r,g,l;(e=W(a.f))&&(e=e&&h(b));if(e)for(b=0;b<d.length;b++)try{k=d[b][0];f=1<d[b].length?d[b].slice(1):[];f=f.concat(a.v);r=k.apply(null,f);g={qacct:a.p,event:"rule"};for(l in r)r.hasOwnProperty(l)&&"qacct"!==l&&(g[l]=r[l]);c(g)}catch(q){}};ka=function(){return aa(0)!==aa(6)?1:0};aa=function(a){a=new Date(2E3,a,1,0,0,0,0);
var c=a.toGMTString(),c=new Date(c.substring(0,c.lastIndexOf(" ")-1));return a-c};R=function(a){return a.replace(/\./g,"%2E").replace(/,/g,"%2C")};B="function"===typeof encodeURIComponent?encodeURIComponent:R;q=function(a){return"undefined"!=typeof a&&null!=a};ba=function(){return Math.round(2147483647*Math.random())};S=function(a){var c="",d=m.cookie,b;if(!d)return c;b=d.indexOf(a+"\x3d");a=b+a.length+1;-1<b&&(c=d.indexOf(";",a),0>c&&(c=d.length),c=d.substring(a,c));return c};la=function(){var a=
"",c=L(),d,b,h;if(1===K)return";fpan\x3du;fpa\x3d";d=T(c);for(b=0;b<G.length;b++)if(G[b]===d)return";fpan\x3du;fpa\x3d";d=new Date;b=S("__qca");if(0<b.length){try{h=+b.split("-")[2],338688E5<d-h&&(m.cookie=["__qca\x3d",b,"; expires\x3d",(new Date(h+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",c].join(""))}catch(e){}a+=";fpan\x3d0;fpa\x3d"+b}0===S("__qca").length&&(b="P0-"+ba()+"-"+d.getTime(),m.cookie=["__qca\x3d",b,"; expires\x3d",(new Date(d.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",
c].join(""),b=S("__qca"),a=0<b.length?a+(";fpan\x3d1;fpa\x3d"+b):a+";fpan\x3du;fpa\x3d");return a};ma=function(a){m.cookie=a+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+L()};L=function(){var a,c,b,h;a=m.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));c=a.split(".");h=c.length;if(3>h)return a;b=c[h-1];return 3>b.length?a:a=c[h-2]+"."+b};ca=function(a,c){var b;for(b=0;b<c.length;b++)a^=c.charCodeAt(b),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};T=function(a){var c;
c=ca(2166136261,a);a=ca(3386659096,a);return Math.round(Math.abs(c*a)/65536).toString(16)};wa=function(a){var c,b;if(a&&"object"===N(a))for(b=0;b<D.length;b++)c=D[b],a.hasOwnProperty(c)&&a[c]&&delete a[c]};V=function(a,c,d){var h={},s=b._qacct,r=null,g="webpage",m="load",y={},t,l,s=c?c.qacct||b._qacct:b._qacct;t=e[s];c?t&&(c=P(c,t)):c=t;s&&delete e[s];wa(c);if(null!=c)for(l in c)y[l]=!0,c.hasOwnProperty(l)&&"string"===typeof l&&"string"===typeof c[l]&&("uid"===l||"uh"===l?(pa()||(r=T(c[l])),delete c[l]):
"qacct"!==l&&(0<c[l].length?h[l+a]=B(c[l]):y[l]=!1,"media"===l&&(g=c[l]),"event"===l&&(m=c[l])));if("string"!==typeof s){if(!q(b._qacct)||0===b._qacct.length)return null;s=b._qacct}if(s){if(t=k[s])for(l in t)"string"===typeof l&&t.hasOwnProperty(l)&&!y[l]&&(h[l+a]=B(t[l]),"media"===l&&(g=t[l]),"event"===l&&(m=t[l]))}else return null;y=f[s];q(y)||(y=3);h["rf"+a]=""+y;"string"===typeof r&&(c.uh=r,h["uh"+a]=B(r));if("webpage"===g&&"load"===m){for(c=0;c<w.qpixelsent.length;c++)if(w.qpixelsent[c]===s&&
!d)return null;w.qpixelsent.push(s)}"ad"===g&&(K=1);h["a"+a]=s;return h};va=function(a){var c=[],b;for(b in a)a[b]&&a.hasOwnProperty(b)&&c.push(b+"\x3d"+a[b]);return c.join(";")};xa=function(){var a=m.getElementsByTagName("meta"),c="",b,h,e,k;for(b=0;b<a.length;b++){e=a[b];if(1E3<=c.length)return c;q(e)&&q(e.attributes)&&q(e.attributes.property)&&q(e.attributes.property.value)&&q(e.content)&&(h=e.attributes.property.value,e=e.content,3<h.length&&"og:"===h.substring(0,3)&&(0<c.length&&(c+=","),k=80<
e.length?80:e.length,c+=R(h.substring(3,h.length))+"."+R(e.substring(0,k))))}return B(c)};na=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};pa=function(){var a=!1;q(b.external)&&(a=b.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());return a||"1"==A.doNotTrack||"yes"===A.doNotTrack||"1"==A.msDoNotTrack};n=function(a,c){var d="function"===typeof encodeURIComponent?"n":"s",h=ba(),e="",
k="",f="",r="",g="",t="u",l="1",v=[],n,z,p,u,x;K=0;q(w.qpixelsent)||(w.qpixelsent=[]);if(q(a))if(n=N(a),"object"===n)z=V("",a,c);else{if("array"===n)for(n=0;n<a.length;n++)p=V("."+(n+1),a[n],c),z=0===n?p:P(z,p)}else"string"===typeof _qacct&&(z=V("",null,c));z&&(n=A.cookieEnabled?"1":"0","undefined"!=typeof A.javaEnabled&&(t=A.javaEnabled()?"1":"0"),q(b._qmeta)&&(k=";m\x3d"+B(b._qmeta),b._qmeta=null),self.screen&&(e=screen.width+"x"+screen.height+"x"+screen.colorDepth),p=new Date,u=ka(),x=la(),b.location&&
b.location.href&&(f=B(b.location.href)),m&&m.referrer&&(g=B(m.referrer)),b.self===b.top&&(l="0"),z.url?r=f:z.url=f,z.ref||(z.ref=g||""),f=xa(),g=va(z),v.push("/pixel;r\x3d"+h+";"+g+x+";ns\x3d"+l+";ce\x3d"+n),v.push((z.ref?"":";ref\x3d")+";je\x3d"+t+";sr\x3d"+e+";enc\x3d"+d+";dst\x3d"+u+";et\x3d"+p.getTime()+";tzo\x3d"+p.getTimezoneOffset()+(r?";ourl\x3d"+r:"")+k+";ogl\x3d"+f),H.push(v),F())};ua=function(a){var c=new Image;a=[b.location.protocol,"//pixel.",qa(v)?"quantserve.com":"quantcount.com",a[0],
";cm\x3d",na(v),a[1]].join("");c.alt="";c.src=a;c.onload=function(){c&&"number"==typeof c.width&&3===c.width&&ma("__qca")}};F=function(){if(v)for(;H.length;)ua(H.shift());else ta()};qa=function(a){return!0===a||1===a||1===a||q(a)&&"approved"===a.consent?!0:!1};ta=function(){if(!q(v)){if(b.top===b.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){ra("getConsent","advertising");return}}else if(b.postMessage&&"object"===typeof JSON){sa("getConsent","advertising");
return}v=1}F()};ra=function(a,c){v=PrivacyManagerAPI.callApi(a,"quantserve.com",L(),"truste.com",c);F()};sa=function(a,c){var d={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:a,self:"quantserve.com",domain:L(),authority:"truste.com",type:c}};if(b.addEventListener)b.addEventListener("message",M,!1);else if(b.attachEvent)b.attachEvent("onmessage",M);else{v=!0;F();return}try{b.top.postMessage(JSON.stringify(d),"*")}catch(h){}r=setTimeout(function(){q(v)||(v=!0,F())},25)};M=function(a){var c=
null;if(a.source===window.top){try{c="object"===typeof JSON&&JSON.parse(a.data)}catch(d){}c&&"object"===typeof c.PrivacyManagerAPI&&(clearTimeout(r),b.removeEventListener?window.removeEventListener("message",M,!1):b.detachEvent&&window.detachEvent("onmessage",M),v=c.PrivacyManagerAPI,F())}};ia=function(){var a=arguments,c,b;C([].slice.call(a));for(b=0;b<a.length;b++)c=a[b],n(c);p.length?Y():I()};C=function(a){var c=N(a);if("array"===c)for(c=0;c<a.length;c++)C(a[c]);else"object"===c&&ga(a.qacct||b._qacct)};
Aa=function(){var a;Q||b._qevents.length||b.ezt.length||"undefined"===typeof _qacct||(n({qacct:b._qacct}),Q=!0);if(!w.evts){for(a in b._qevents)b._qevents.hasOwnProperty(a)&&n(b._qevents[a]);for(a in b.ezt)b.ezt.hasOwnProperty(a)&&n(b.ezt[a]);b._qevents={push:ia};b.ezt.push=function(){var a=arguments,d;if(q(b.queueManager))for(d=0;d<a.length;d++)b.queueManager.push(a[d]);else ia.apply(this,arguments)};w.evts=1}};Z=function(a){var c;a&&(c=Ba(a),C(a),b._qevents.push(c))};ja=function(a){a.push=function(){C([].slice.call(arguments));
Y();return[].push.apply(a,arguments)}};U=function(){q(b._qevents)||(b._qevents=[]);q(b.ezt)||(b.ezt=[]);Z(b._qoptions);Z(b.qcdata);Z(b.smarttagdata);w.evts||(ja(b._qevents),ja(b.ezt));C(b.ezt);C(b._qevents);C({qacct:b._qacct});b._qoptions=null;p.length?Y():I();J=!0};b.quantserve=b.quantserve||U;w.quantserve=U;return w}(window);
try{__qc("hasRules","p-fw53_-Tq3MNK1")||function(b,D,m){var A="twitter:title og:title title author authors article:author article:authors bt:author bt:authors sailthru.author sailthru.authors sailthru.title lv:author lv:authors lv:title".split(" "),G=function(b){return b.replace(/^[\s\ufeff\xA0]+|[\s\ufeff\xA0]+$/g,"")},J=function(b){return{}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()},Q=function(b,k){var e,f;a:{for(e=0;e<A.length;e++)if(A[e]===b){e=!1;break a}e=!0}if(!k)return k;if(e){f=
k.split(",");for(e=0;e<f.length;e++)f[e]=G(f[e]);return f}return G(k.replace(/,+/g," "))},K=function(b,k,e){return b?"nc"===b?!k||!e||0>k.indexOf(e):"eq"===b?k===e:"sw"===b?0===k.indexOf(e):"ew"===b?(b=k.length-e.length,k=k.lastIndexOf(e,b),-1!==k&&k===b):"c"===b?0<=k.indexOf(e):!1:!1},H=function(b){var k=m.createElement("a");k.href=b;return k},g=function(b,k,e){var f;f=D.top===D.self?m.location.href:H(m.referrer).href;K(k,f,e)?b(f):b(!1)},E=function(b,f,e){f=document.getElementsByTagName("meta");
for(var g,m,p=[],u=0;u<f.length;u++)g=f[u],m=g.getAttribute("name")||g.getAttribute("property"),m==e&&(p=p.concat(Q(e,g.getAttribute("content"))));0<p.length?b(p):b(!1)},p=function(b){return{labels:b}},f=function(b){return"array"===J(b)?p(b.join(",")):p(""+b)},u=function(b,f){var e=[],g;if("array"===J(f)){for(g=0;g<f.length;g++)e.push(b+"."+f[g]);return p(e.join(","))}return p(b+"."+f)},x=["rules",[b,null,[[f,"_campaign.branded.Podcast.Umpqua Bank.Open Account.Episode 301"]],[[g,"c","slate.com/podcasts/open-account/the-nuances-of-poverty--dr--donna-beegle.html"]]],
[b,null,[[u,"Author"]],[[E,"exactmatch","author"]]],[b,null,[[u,"Title"]],[[E,"exactmatch","og:title"]]],[b,null,[[f,"Technology.Future Tense"]],[[g,"c","future_tense"]]],[b,null,[[f,"Slate Plus"]],[[g,"c","slate.com/plus"]]],[b,null,[[f,"Arts.Brow Beat"]],[[g,"c","slate.com/blogs/browbeat"]]],[b,null,[[f,"Arts.Culturebox"]],[[g,"c","culturebox"]]],[b,null,[[f,"News \x26 Politics.Cover Story"]],[[g,"c","cover_story"]]],[b,null,[[f,"Business.Moneybox"]],[[g,"c","slate.com/blogs/moneybox"]]],[b,null,
[[f,"News \x26 Politics.The Slatest"]],[[g,"c","the_slatest"]]],[b,null,[[f,"Life.Normal"]],[[g,"c","slate.com/blogs/normal"]]],[b,null,[[f,"Life.Outward"]],[[g,"c","slate.com/blogs/outward"]]],[b,null,[[f,"Life.Lexicon Valley"]],[[g,"c","slate.com/blogs/lexicon_valley"]]],[b,null,[[f,"Sports"]],[[g,"c","slate.com/articles/sports"]]],[b,null,[[f,"Video"]],[[g,"c","slate.com/articles/video"]]],[b,null,[[f,"Podcasts"]],[[g,"c","slate.com/articles/podcasts"]]],[b,null,[[f,"Health \x26 Science"]],[[g,
"c","slate.com/articles/health_and_science"]]],[b,null,[[f,"Blogs.Atlas Obscura"]],[[g,"c","slate.com/blogs/atlas_obscura"]]],[b,null,[[f,"Double X.The XX Factor"]],[[g,"c","slate.com/blogs/xx_factor"]]],[b,null,[[f,"Blogs.Bad Astronomy"]],[[g,"c","slate.com/blogs/bad_astronomy"]]],[b,null,[[f,"Photos"]],[[g,"c","slate.com/blogs/behold"]]],[b,null,[[f,"Life.Dear Prudence"]],[[g,"c","dear_prudence"]]],[b,null,[[f,"News \x26 Politics.Cover Story"]],[[g,"c","cover-story"]]]];__qc.apply(null,x);(function(){var f=
function(){return D.top===D.self?m.location.href:H(m.referrer).href},g=f();setInterval(function(){var e=f();e!==g&&(g=e,__qc.apply(null,x),__qc("push",{qacct:b,event:"load"},!0))},2E3)})()}("p-fw53_-Tq3MNK1",window,document)}catch(nfe$$3){}quantserve();